apiVersion: v1
kind: Deployment
metadata: 
  name: hello-deployment
  labels:
    app: hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: docker.io/danlh/sandbox/hello-world:latest
        ports:
        - containers: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  type: LoadBalancer
  ports:
    - port: 8501
  selector:
    app: hello-world
  