name: Deploy to Kubernetes

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
# Updated all creds
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Apply
        env:
          client_id: ${{ secrets.client_id }}
          client_secret: ${{ secrets.client_secret }}
        working-directory: nginx-test/Terraform
        run: |
          terraform init
          terraform apply -var "client_id=${client_id}" -var "client_secret=${client_secret}" -auto-approve

      - name: Set up Kubernetes CLI
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: AKSsandbox
          cluster-name: sandboxcluster

      - name: Run kubectl commands
        run: |
          kubectl apply -f /nginx-test/deployment.yml
          kubectl apply -f /nginx-test/service.yml
